# Generated by Django 4.2.8 on 2024-01-03 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('ratings', models.DecimalField(decimal_places=1, max_digits=3)),
                ('numReviews', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('countInStock', models.IntegerField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
